### PR TITLE
Add b-stats archive

### PR DESCRIPTION
**Pull request by bstats**
Technically it's not foolfuuka but I've made the URLs and API work. Some boards have been archiving longer than many other existing archives. Files aren't indexed yet but are mostly saved, so I may add that in later.

### CODE REVIEW

**Comment by bui** [comment]
You're missing /full_image/ (used by 4chan-x)

https://archive.b-stats.org/b/full_image/1429376177506.png
https://fgts.jp/b/full_image/1429376177506.png

**Comment by bstats** [comment]
Is that not just for archives with boards listed in `files`?

**Comment by MayhemYDG** [comment]
Not taking more chances with /b/ I see?
The `uid` should be `28`. `26` was poweredby.moe, and `27` was 4ch.be.
633f1cbe551a4843ce0c4db1053b0de06addb730
645f24b1d87ffd05ac078a7683146524a55e93f7
Looks good otherwise.

**Comment by bstats** [comment]
/b/ is only selectively archived, so wouldn't be useful for most people. I'll fix the `uid`

**Comment by MayhemYDG** [comment]
Great, thanks!

**Pull request merged**
