### PR TITLE
Removing Love is Over

### PR DESCRIPTION
**Pull request by theBladeee**
We're done for good this time. Thanks for all the fond memories!

### CODE REVIEW

**Comment by MayhemYDG** [comment]
I guess you could say that love *is* over. 🤔

**Comment by theBladeee** [comment]
Didn't you post this last time? Granted that was like 4 years ago. 🤔

**Comment by MayhemYDG** [comment]
I wouldn't be surprised if I did.

**Comment by antonizoon** [comment]
theBladeee: Will you be able to post backups like we did last time? Contact VoH or me at antonizoon@bibanon.org if you need any assistance with uploading dumps to the internet archive.

**Comment by theBladeee** [comment]
Got the quote for the cereal box either way. [](https://i.imgur.com/jgVmWQy.png)

**Comment by theBladeee** [comment]
@antonizoon I don't particularly have any interest in messing with the site anymore, but if you want to contact me I can just hand over the keys so you can do it yourself. I believe there is about a week left on the server. Blade#8675 is my Discord, but if you have a contact email I can contact you there as well.

**Comment by antonizoon** [comment]
Unfortunately, the server got deleted unexpectedly upon the cancellation of Loveisover's server, where a week's cooldown was expected.

Our latest full backups of loveisover are from 20170903. Only full images also archived by Nyafuu were transferred there. SQL dumps for 20170903 will also be made public when we scrub the ghostpost ip addresses.

https://archive.org/details/loveisover-20170903

This may represent a loss of /d/, /i/, /lgbt/, /t/ full images from 20170903 to 2018-03-29. Otherwise, threads and thumbnails since then are still accessible at the full 4chan archiver https://archived.moe.

These boards also have no active 4chan archiver currently.

**Comment by antonizoon** [comment]
Archiveofsins.com will be taking over i, lgbt, t, and u full images. d will be on desuarchive. https://archiveofsins.com/talk/thread/30/

**Comment by MayhemYDG** [comment]
@antonizoon mind editing the json to add these boards to archiveofsins?

**Pull request merged**
