### PR TITLE
Update archives.json

### PR DESCRIPTION
**Pull request by pleebe**
reports plugin appears to be on archived.moe, thebarchive.com, and archiveofsins.com

### CODE REVIEW

**Comment by ccd0** [comment]
Also HTTPS.

**Comment by ccd0** [comment]
And they should be moved up in accordance with the HTTPS-on-top policy (https://github.com/MayhemYDG/archives.json/pull/50).

**Comment by pleebe** [comment]
like that?

**Comment by ccd0** [comment]
Above 4tan also, since they're older. So it would be sorted first by HTTPS support and then by archive age.

**Comment by pleebe** [comment]
I see

**Comment by ccd0** [comment]
Looks good to me, although it might be a good idea to squash the changes to one commit.

**Comment by pleebe** [comment]
Indeed. Whoever merges this can squash.

**Comment by ccd0** [comment]
I'm assuming it's okay for me to merge this.
43871e82ccc932331375f10b52b6a9a8467d1bb8

**Pull request closed without merging**
