### PR TITLE
Create archives.md

### LINKED ISSUE #35: On the Allocation of Archive IDs
Should we have a list of all of the allocated archive IDs (or at very least the newest archive ID to use if adding to the list)? This will make the lives of future archive maintainers much easier, and has been an issue (bad pun) in the past: 
https://github.com/MayhemYDG/archives.json/pull/1#discussion_r18681710, https://github.com/MayhemYDG/archives.json/pull/24/commits/bd035f582c5d2b13610fa30d5f2d257fa23b310e, https://github.com/MayhemYDG/archives.json/pull/29#issuecomment-204734981, etc.

Here's the plan if you agree to the list idea:
- We come up with how we want to do it (JSON for programmatic access or just a nice markdown file, I recommend the latter), and implement a template for it (for just one sample archive).
- I (or someone else, if anybody wants to) go through the git commit history and add them to the list and just make a PR referencing this issue when I finish.
- Update the list whenever a new archive is added.

And/or if we want to have the newest archive ID to use then we can just include that somewhere in the [CONTRIBUTING.md](https://github.com/MayhemYDG/archives.json/blob/gh-pages/CONTRIBUTING.md).

### PR DESCRIPTION
**Pull request by r3c0d3x**
Meant to make this myself at some point. Thanks @bstats!

Closes #35.

I will eventually make something a bit more detailed that also keeps track of boards archived over time, the date it was added/removed, etc., but this should be fine for now.

### CODE REVIEW

**Comment by bstats** [comment]
I'm not sure `boards.csv` makes sense for the name of this list (since right now it is just a list of archive allocations). Maybe `archive_ids.csv`, or something else that doesn't bring the connotation of being a list of boards rather than archive websites.

**Comment by MayhemYDG** [comment]
What bstats said.
Also Foolz got replaced with archive.moe, while keeping the same id, did you check the first appearance in a commit instead of the last? There might be errors in that case.

**Comment by r3c0d3x** [comment]
Probably shouldn't have made that commit after nearly being up for 20 hours straight. Just renamed everything, they should be good now. Sorry!

@bstats contributed the table, so I'm not sure how they went about doing it, but I just replaced Foolz with archive.moe. If there are any other errors, please mention them and I'll update the file.

**Comment by MayhemYDG** [comment]
Checked quickly with the archives that are still alive, and I found this:

```csv
10,warosu,fuuka.warosu.org
```

It's `warosu.org` now. I don't feel like checking everything :^(

The contributing guide should also mention to check this list.

Also I'm not sure a .csv is what we want. I think a simple markdown file with a table layout would be better imo.

**Comment by r3c0d3x** [comment]
Creating one now.

**Comment by r3c0d3x** [comment]
GitHub appears to only allow GFM (GitHub Flavored Markdown, which allows us to make tables) in certain scenarios, not including ours (separate file). We might be able to get away with having it in the README, although I'm not sure we'd want to do that.

**Comment by bstats** [comment]
b-stats doesn't actually use FoolFuuka. It has a FoolFuuka compatibility layer, so it says it uses FoolFuuka in archives.json in order to work seamlessly with 4chanX

**Comment by r3c0d3x** [comment]
@bstats I know, I just linked to FoolFuuka to decrease the confusion from developers (or whoever our target audience may be) from having to think about the possibility of supporting another API. Do you want me to change it to link to your project? I could also just have a note linking to your project, but mentioning that it implements the FoolFuuka API.

**Comment by bstats** [comment]
@r3c0d3x If people are thinking about using APIs, they'll use archives.json, not a .md full of dead archives where the API doesn't matter anyway. You should link to the code that each archive uses/used.

**Comment by r3c0d3x** [comment]
I guess you're right, but

> not a .md full of dead archives

I'd consider it more of a reference page, but whatever. I've changed it so that it links to [your repo](https://github.com/bstats/b-stats).

Are there any other changes I should make?

**Comment by bstats** [comment]
> Are there any other changes I should make?
Add archived.moe.

Dead/alive is a good idea; it's somewhat redundant since you can just check archives.json, but it doesn't hurt to have more information.

**Comment by MayhemYDG** [comment]
I can't possibly be bothered to check if everything is correct, but it looks good otherwise.
Let me know when it's good to merge.

**Comment by r3c0d3x** [comment]
@MayhemYDG It's ready to be merged. I'm not really going to include dead/alive as bstats's comment about it being redundant is completely true. I'll mark this and the related issue as closed when it's merged.

**Pull request merged**
